### PR TITLE
Changes Index File

### PR DESCRIPTION
**Pull request by 23SumiTM**
added Privacy and Terms And Condition Links

### CODE REVIEW

**Review by renners7777 — COMMENTED** [review]
These changes seem fine to me. Are you offering to complete these sections as well?

**Review by renners7777 — COMMENTED** [review]
These changes seem fine to me.

**Comment by 23SumiTM** [comment]
No  Sir ,Because  I am just new on  Github   
I am in learning phase.

**Comment by 23SumiTM** [comment]
If This Changes Seems Fine To You Sir.
Kindly Merge This PR.

**Review by drewlearns — APPROVED** [review]

**Pull request merged**
